version: "3.5"
services:
  api:
    image: formomosan/go_stop:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "80:8000"
    environment:
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
      JWT_SECRET_KEY: /run/secrets/jwt_secret_key
      POSTGRES_DB: go_stop_go
      POSTGRES_HOST: db
      ENV: prod
    depends_on:
      - db
    secrets:
      - postgres_user
      - postgres_password
      - jwt_secret_key
  db:
    image: postgres
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: go_stop_go
    ports:
      - "5432"
    secrets:
      - postgres_user
      - postgres_password

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  jwt_secret_key:
    external: true
